baseURL = 'http://consulminds.com/'
languageCode = 'en-in'
title = 'ConsulMinds Technologies'

theme = 'hugo-universal-theme'

[params]
    disabled_logo = false
    logo_text = 'CONSULMINDS TECHNOLOGIES'
    logo = 'img/logo.png'
    logo_small = 'img/logo.png'

    email = "info@consulminds.com"
    contact_form_ajax = false

    defaultDescription = "ConsulMinds Technologies - Tech consulting"

    about_us = "<p>We are software services company based out of Pune. We develop products and solutions for customers.</p>"

    contact_url = "/contact"
    address = """<p class="text-uppercase"><strong>ConsulMinds Technologies Private Limited.</strong>
        <br>308, Opel Falaq CHS,
        <br>Kondhwa (Kh), Pune
        <br>411048
        <br>
        <strong>India</strong>
      </p>
      """

    copyright = "Copyright (c) 2022 - 2023, ConsulMinds Technologies Pvt Ltd; all rights reserved."

[params.topbar]
    enable = true
    text = """
    <p class="hidden-sm hidden-xs">Reach us at info@consulminds.com.</p>
    <p class="hidden-md hidden-lg">
        <a href="tel:+91 9028 817 212" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
        <a href="mailto:info@consulminds.com" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
    </p>
    """

# Menu bar
# [[menu.main]]
#     name       = "About Us"
#     identifier = "menu.about"
#     url        = "/#"
#     weight     = 1

# [[menu.main]]
#     name       = "Consulting"
#     identifier = "menu.services"
#     url        = "/#"
#     weight     = 2

# [[menu.main]]
#     name       = "Contact Us"
#     identifier = "menu.contact"
#     url        = "/#"
#     weight     = 3

# [[menu.main]]
#     name       = "Blog"
#     identifier = "menu.blog"
#     url        = "/#"
#     weight     = 4


# Social Links

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/consulminds"
    pre = "<i class='fas fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "LinkedIn"
    url = "https://www.linkedin.com/company/consulminds"
    pre = "<i class='fas fa-2x fa-linkedin'></i>"

[params.features]
    enable = true
    cols = 3

[params.testimonials]
    enable = false
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.clients]
    enable = true
    title = "Our Partners"
    subtitle = "We have proudly collaborated with the following companies."
